#!/bin/bash
DIR="$1"
if [ "$DIR" != "" ] && [[ ! -d "$DIR" ]]
then
	echo "Target not found: $DIR"
	exit 1
fi
[ "$DIR" != "" ] && pushd "$DIR" > /dev/null
du -xP -d1 -BM 2>/dev/null | sort -nk1 | tail -n 20
[ "$DIR" != "" ] && popd "$DIR" > /dev/null
